### ISSUE TITLE
"pip install privacyscanner" schlägt fehl (gleiches Verhalten als User und als root)

### ISSUE THREAD

**Issue by capricorn72** [PrivacyScore/privacyscanner#15]
HOST ~ # python3 -m venv venv
HOST ~ # source venv/bin/activate
(venv) HOST ~ # pip install privacyscanner
The directory '/home/pinguin/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/pinguin/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting privacyscanner
  Downloading https://files.pythonhosted.org/packages/12/18/6e509a26cb1fa17c4a9d5a6f42fa2ef20e60e8a9cc146ee0d472a7661e87/privacyscanner-0.5.3-py3-none-any.whl (61kB)
    100% |████████████████████████████████| 71kB 8.8MB/s 
Requirement already satisfied: pychrome in ./venv/lib/python3.6/site-packages (from privacyscanner)
Requirement already satisfied: toposort in ./venv/lib/python3.6/site-packages (from privacyscanner)
Collecting psutil (from privacyscanner)
  Downloading https://files.pythonhosted.org/packages/c7/01/7c30b247cdc5ba29623faa5c8cf1f1bbf7e041783c340414b0ed7e067c64/psutil-5.5.1.tar.gz (426kB)
    100% |████████████████████████████████| 430kB 3.4MB/s 
Requirement already satisfied: dnspython in ./venv/lib/python3.6/site-packages (from privacyscanner)
Requirement already satisfied: adblockeval in ./venv/lib/python3.6/site-packages (from privacyscanner)
Requirement already satisfied: tldextract in ./venv/lib/python3.6/site-packages (from privacyscanner)
Requirement already satisfied: psycopg2-binary in ./venv/lib/python3.6/site-packages (from privacyscanner)
Requirement already satisfied: pillow in ./venv/lib/python3.6/site-packages (from privacyscanner)
Requirement already satisfied: requests in ./venv/lib/python3.6/site-packages (from privacyscanner)
Requirement already satisfied: geoip2 in ./venv/lib/python3.6/site-packages (from privacyscanner)
Requirement already satisfied: cryptography in ./venv/lib/python3.6/site-packages (from privacyscanner)
Requirement already satisfied: click>=6.0 in ./venv/lib/python3.6/site-packages (from pychrome->privacyscanner)
Requirement already satisfied: websocket-client>=0.44.0 in ./venv/lib/python3.6/site-packages (from pychrome->privacyscanner)
Requirement already satisfied: setuptools in ./venv/lib/python3.6/site-packages (from tldextract->privacyscanner)
Requirement already satisfied: idna in ./venv/lib/python3.6/site-packages (from tldextract->privacyscanner)
Requirement already satisfied: requests-file>=1.4 in ./venv/lib/python3.6/site-packages (from tldextract->privacyscanner)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.6/site-packages (from requests->privacyscanner)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in ./venv/lib/python3.6/site-packages (from requests->privacyscanner)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./venv/lib/python3.6/site-packages (from requests->privacyscanner)
Requirement already satisfied: maxminddb>=1.4.0 in ./venv/lib/python3.6/site-packages (from geoip2->privacyscanner)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in ./venv/lib/python3.6/site-packages (from cryptography->privacyscanner)
Requirement already satisfied: asn1crypto>=0.21.0 in ./venv/lib/python3.6/site-packages (from cryptography->privacyscanner)
Requirement already satisfied: six>=1.4.1 in ./venv/lib/python3.6/site-packages (from cryptography->privacyscanner)
Requirement already satisfied: pycparser in ./venv/lib/python3.6/site-packages (from cffi!=1.11.3,>=1.8->cryptography->privacyscanner)
Installing collected packages: psutil, privacyscanner
  Running setup.py install for psutil ... error
    Complete output from command /home/pinguin/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2932_p72/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-v9mhs85k-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pinguin/venv/include/site/python3.6/psutil:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psosx.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_common.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psaix.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/__init__.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psposix.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_compat.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.6/psutil
    creating build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_memory_leaks.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.6/psutil/tests
    running build_ext
    building 'psutil._psutil_linux' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/psutil
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=551 -DPSUTIL_LINUX=1 -I/home/pinguin/venv/include -I/usr/include/python3.6m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.6/psutil/_psutil_common.o
    psutil/_psutil_common.c:9:10: fatal error: Python.h: Datei oder Verzeichnis nicht gefunden
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/pinguin/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2932_p72/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-v9mhs85k-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pinguin/venv/include/site/python3.6/psutil" failed with error code 1 in /tmp/pip-build-2932_p72/psutil/
(venv) HOST ~ #

**Comment by wichmannpas** [comment]
You need to install the python3 header files. For Debian, they can be installed with the package `python3-dev`.
Feel free to reopen if this does not solve your issue.
