### ISSUE TITLE
Why/Where is debugging_port for chrome altered when running the scan utility?

### ISSUE THREAD

**Issue by maltekrupa** [PrivacyScore/privacyscanner#20]
Hi,

what I observed throughout the codebase is the mentioning of `debugging_port` which is set to the default chrome debugging port `9222`. I also found [the place](https://github.com/PrivacyScore/privacyscanner/blob/master/privacyscanner/scanmodules/chromedevtools/__init__.py#L47) that increments that number based on the worker_id ... but to my confusion I do not understand why this value is incremented to `9223` when using the `scan` utility. Can someone please point me in the right direction?

Edit:
To give a little background on my question: I want to run the privacyscanner in a docker container and decouple the chrome process in another container so I can conveniently pack them both in a kubernetes pod later.

Thanks!

**Comment by hprid** [comment]
The port was incremented to 9223 because the lock file number for concurrent execution of the scan command started at 1 instead of 0. Commit 1211e7291c9e1545344670c1239d72b4ac228d6f fixes that.
