### ISSUE TITLE
GeoLite2 no longer available via public download

### ISSUE THREAD

**Issue by johnp** [PrivacyScore/privacyscanner#22]
MaxMind now[0] requires registration and obtainment of a free license key to be able to download the database. Furthermore, licensing changed from CC BY-SA 4.0 to a custom EULA. There's still a [Direct Download](https://dev.maxmind.com/geoip/geoipupdate/#Direct_Downloads) method, but that also requires a license key and I don't know if a project-wide key satisfies the new usage requirements.

I'm surprised the dns module is still working, since [`GEOIP_MAX_AGE`](https://github.com/PrivacyScore/privacyscanner/blob/4a2a01563473a6f6c1ee27ead15de698fed4016a/privacyscanner/scanmodules/dns.py#L17) is set to three days and the URL doesn't even resolve any more (NXDOMAIN)...

[0] [https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/](https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/)

**Comment by hprid** [comment]
Fixed in 0.8.0. See README.md for details how to enter the license key.
