### ISSUE TITLE
What's the schema supposed to look like for the `run_workers` part of the script?

### ISSUE THREAD

**Issue by maltekrupa** [PrivacyScore/privacyscanner#4]
Hi,

I'm getting crazy here trying to figure out a valid schema that makes it possible to use the `run_workers` command. Yesterday I [hacked something together](https://github.com/temal-/privacyscanner/blob/af326a0311482df4be8b04c558baa47e50d36e7c/migrations/versions/4a856be123e7_initial.py) that kind of works for a single module but as soon as I try to add a second module everything falls apart. I'm playing around with it for way too long now, so I wanted to ask you if it would be possible to add the database schema to this repo? 

Thanks a lot in advance!

Malte

**Comment by hprid** [comment]
Hi Malte,

Here is a [gist](https://gist.github.com/hprid/89d5df87bf14bde2e672641368d8c5f0) with the relevant models from the privacyscore version which is currently in development as well as a pg_dump from the database. I hope that helps for now.

I will extract the relevant part together some documentation later on, and add it to the repository.

Feel free to ask us right away if you have any questions.

**Comment by hprid** [comment]
There is now a schema.sql with commit aa7f3e85f97c984321a85f66a050f52b50ff47dd. Documentation will follow the next days.

**Comment by maltekrupa** [comment]
Thanks a lot!
